### ISSUE TITLE
Error: Command failed: powershell.exe

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [icflorescu/expose-wsl#7]
```powershell
root> npx expose-wsl@latest
Need to install the following packages:
expose-wsl@1.1.3
Ok to proceed? (y) y
                                                   _
   _____  ___ __   ___  ___  ___     __      _____| |
  / _ \ \/ / '_ \ / _ \/ __|/ _ \____\ \ /\ / / __| |
 |  __/>  <| |_) | (_) \__ \  __/_____\ V  V /\__ \ |
  \___/_/\_\ .__/ \___/|___/\___|      \_/\_/ |___/_|
           |_|

⏳ Downloading WSLHostPatcher... extracting... running... done ✔️
🎉 WSL should be accessible at: 'Select-Object' is not recognized as an internal or external command,
operable program or batch file.
failed to run ❌
🔥 Please report this issue at https://github.com/icflorescu/expose-wsl/issues
Error: Command failed: powershell.exe 'Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $(Get-NetConnectionProfile | Select-Object -ExpandProperty InterfaceIndex) | Select-Object -ExpandProperty IPAddress'
    at checkExecSyncError (node:child_process:887:11)
    at execSync (node:child_process:959:15)
    at file:///C:/Users/ahmetcetinkaya/AppData/Local/npm-cache/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/run.js:43:3 {
  status: 255,
  signal: null,
  output: [ null, null, null ],
  pid: 11448,
  stdout: null,
  stderr: null
}
```

But the command works when in terminal.
```powershell
root> powershell.exe 'Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $(Get-NetConnectionProfile | Select-Object -ExpandProperty InterfaceIndex) | Select-Object -ExpandProperty IPAddress'
192.168.0.3
```

**Comment by ryuujo1573** [comment]
Simply put.
> No installation required. Simply run the following command in your **WSL terminal** before starting your applications:

It seems you are doing that in windows rather than wsl.

**Comment by ahmet-cetinkaya** [comment]
@ryuujo1573, I also tried it in WSL terminal:
I use Debian 11 with Genie.
```sh
root@ahmetcetinkaya-wsl:~# neofetch
       _,met$$$$$gg.          root@ahmetcetinkaya-wsl
    ,g$$$$$$$$$$$$$$$P.       -----------------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) on Windows 10 x86_64
 ,$$P'              `$$$.     Kernel: 5.10.102.1-microsoft-standard-WSL2
',$$P       ,ggs.     `$$b:   Uptime: 2 mins
`d$$'     ,$P"'   .    $$$    Packages: 889 (dpkg)
 $$P      d$'     ,    $$P    Shell: sh
 $$:      $$.   -    ,d$$'    CPU: Intel i7-1065G7 (8) @ 1.497GHz
 $$;      Y$b._   _,d$P'      Memory: 968MiB / 18995MiB
 Y$$.    `.`"Y$$$$P"'
 `$$b      "-.__
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""

root@ahmetcetinkaya-wsl:~# node -v
v20.8.1
root@ahmetcetinkaya-wsl:~# npm -v
10.2.1
root@ahmetcetinkaya-wsl:~# npx expose-wsl@latest
Need to install the following packages:
expose-wsl@1.1.5
Ok to proceed? (y) y
                                                   _
   _____  ___ __   ___  ___  ___     __      _____| |
  / _ \ \/ / '_ \ / _ \/ __|/ _ \____\ \ /\ / / __| |
 |  __/>  <| |_) | (_) \__ \  __/_____\ V  V /\__ \ |
  \___/_/\_\ .__/ \___/|___/\___|      \_/\_/ |___/_|
           |_|

⏳ Downloading WSLHostPatcher... extracting... running... done ✔️
🎉 WSL should be accessible at: /bin/sh: 1: powershell.exe: not found
failed to run ❌
🔥 Please report this issue at https://github.com/icflorescu/expose-wsl/issues
Error: Command failed: powershell.exe 'Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $(Get-NetConnectionProfile | Select-Object -ExpandProperty InterfaceIndex) | Select-Object -ExpandProperty IPAddress'
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at file:///root/.npm/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/run.js:43:3 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 1425,
  stdout: null,
  stderr: null
}
root@ahmetcetinkaya-wsl:~#
```

Since it was trying to use Powershell, I give an example from Windows while preparing the issue.

**Comment by icflorescu** [comment]
Oh, I see. In this case, the wsl host patcher actually worked, but the `powershell.exe` windows executable couldn't be called to determine the external IP address, so you'll have to find it yourself...

**Comment by ahmet-cetinkaya** [comment]
> so you'll have to find it yourself...

Can I find it with the following command?
```sh
ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
```
---

```sh
root@ahmetcetinkaya-wsl:~# npx expose-wsl@latest
Need to install the following packages:
expose-wsl@1.1.6
Ok to proceed? (y) y
                                                   _
   _____  ___ __   ___  ___  ___     __      _____| |
  / _ \ \/ / '_ \ / _ \/ __|/ _ \____\ \ /\ / / __| |
 |  __/>  <| |_) | (_) \__ \  __/_____\ V  V /\__ \ |
  \___/_/\_\ .__/ \___/|___/\___|      \_/\_/ |___/_|
           |_|

⏳ Downloading WSLHostPatcher... extracting... running... done ✔️
🎉 WSL should be accessible at: /bin/sh: 1: powershell.exe: not found
💡 The patcher worked, but powershell.exe could not be called to determine the IP address of the WSL interface; you'll have to figure it out yourself.
💡 Make sure to restart your server application(s) before trying to access them!
root@ahmetcetinkaya-wsl:~# ip addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
172.21.90.189
```

After running the above command, the output shows the IP address as `172.21.90.189`.

I can access the application using the `172.21.90.189` address on the same device. However, I am unable to access the application using the same address on my mobile phone, even though it is on the same network.

I have also tried adding a netsh interface to windows and using the `192.168.0.3` address in my mobile phone, but the issue remains:
```sh
netsh interface portproxy add v4tov4 listenport=80 listenaddress=0.0.0.0 connectport=80 connectaddress=172.21.90.189
```

**Comment by ryuujo1573** [comment]
Mine works well at installation stage.
Yet it did not work to expose my wsl service listening at `0.0.0.0` et idk why...
🤔 

After some research, I make it through running a frp C/S on linux/win after a simple configuration.

<details>
<summary>FWIW:</summary>

In <code>frpc.ini</code> on Linux
<pre class="notranslate"><span class="pl-en">[common]</span>
<span class="pl-k">server_addr</span> = <span class="pl-s"><span class="pl-pds">"</span>{{ .Envs.HOSTIP_WIN }}<span class="pl-pds">"</span></span>
<span class="pl-k">server_port</span> = 7000

<span class="pl-c"><span class="pl-c">;</span> [fxxk_nat]</span>
<span class="pl-c"><span class="pl-c">;</span> type = https</span>
<span class="pl-c"><span class="pl-c">;</span> custom_domains = "localhost"</span>

<span class="pl-c"><span class="pl-c">;</span> plugin = https2https</span>
<span class="pl-c"><span class="pl-c">;</span> plugin_local_addr = https://127.0.0.1:5173</span>

<span class="pl-en">[range:fuck_nat]</span>
<span class="pl-k">type</span> = tcp
<span class="pl-k">local_ip</span> = 127.0.0.1
<span class="pl-k">local_port</span> = 5173-5175
<span class="pl-k">remote_port</span> = 5173-5175</pre>

<p>It's fine to run a frp service, but managing frpc config manually could be messy.</p>
<p>Maybe this script can be leveraged with frp? :-|</p>

</details>
